export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const NOTIFY_USER = "NOTIFY_USER";
export const DISABLE_BALANCE_ON_ADD = "DISABLE_BALANCE_ON_ADD";
export const DISABLE_BALANCE_ON_EDIT = "DISABLE_BALANCE_ON_EDIT";
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
